# GET /todos
GET http://localhost:3001/todos
Content-Type: application/json
###

# POST /todo/new
POST http://localhost:3001/todo/new
Content-Type: application/json

{
  "text": "5. görev"
}
###

# DELETE /todo/delete/:id
DELETE http://localhost:3001/todo/delete/639269850bb629bb26324f97
Content-Type: application/json
###


# DELETE /todos/delete/all
DELETE http://localhost:3001/todos/delete/all
Content-Type: application/json
###

# PUT /todo/update/:id
PUT http://localhost:3001/todo/update/639269850bb629bb26324f97
Content-Type: application/json

{
  "text": "First TODO updated 1"
}
###

# GET /todo/complete/:id
GET http://localhost:3001/todo/complete/6392787a66b06eebe1b2fddb
Content-Type: application/json
###
